CREATE TABLE IF NOT EXISTS public.medicos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    crm character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    logradouro character varying(255) COLLATE pg_catalog."default" NOT NULL,
    bairro character varying(255) COLLATE pg_catalog."default" NOT NULL,
    cep character varying(255) COLLATE pg_catalog."default" NOT NULL,
    cidade character varying(255) COLLATE pg_catalog."default" NOT NULL,
    uf character varying(255) COLLATE pg_catalog."default" NOT NULL,
    numero character varying(255) COLLATE pg_catalog."default",
    complemento character varying(255) COLLATE pg_catalog."default",
    especialidade character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT medicos_pkey PRIMARY KEY (id),
    CONSTRAINT crm_unique UNIQUE (crm),
    CONSTRAINT email_unique UNIQUE (email),
    CONSTRAINT medicos_especialidade_check CHECK (especialidade::text = ANY (ARRAY['ORTOPEDIA'::character varying::text, 'CARDIOLOGIA'::character varying::text, 'GINECOLOGIA'::character varying::text, 'DERMATOLOGIA'::character varying::text]))
);