CREATE TABLE IF NOT EXISTS public.pacientes
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    telefone character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cpf character varying(14) COLLATE pg_catalog."default" NOT NULL,

    logradouro character varying(100) COLLATE pg_catalog."default" NOT NULL,
    bairro character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cep character varying(9) COLLATE pg_catalog."default" NOT NULL,
    cidade character varying(100) COLLATE pg_catalog."default" NOT NULL,
    uf character varying(2) COLLATE pg_catalog."default" NOT NULL,
    numero character varying(20) COLLATE pg_catalog."default",
    complemento character varying(100) COLLATE pg_catalog."default",

    ativo smallint NOT NULL DEFAULT 1,

    CONSTRAINT pacientes_pkey PRIMARY KEY (id),
    CONSTRAINT pacientes_email_unique UNIQUE (email),
    CONSTRAINT pacientes_cpf_unique UNIQUE (cpf)
);